# Site settings
title: LC2 14-15
email: andreapavan89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  University of Udine. Esercizi del corso di Linguaggi e Compilatori a.a. 2014-2015
baseurl: "/compilatori" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pavandrea
github_username:  andreapavan

# Build settings
markdown: kramdown
